# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients_list',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
