# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_toolbox', '0002_auto_20170329_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_temperature_celsius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
