# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('creation_date', models.DateField(verbose_name=b'creation date')),
                ('process_description', models.TextField()),
                ('cooking_temperature_celsius', models.IntegerField(default=0)),
                ('preparation_time_minutes', models.IntegerField(default=0)),
                ('presentation_image_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_quantity', models.CharField(max_length=100)),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_toolbox.Ingredients_List')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_toolbox.Recipe')),
            ],
        ),
    ]
