# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_temperature_celsius',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_minutes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='presentation_image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='ingredient_quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
